/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface G21ResponsiveImage {
    }
}
declare global {
    interface HTMLG21ResponsiveImageElement extends Components.G21ResponsiveImage, HTMLStencilElement {
    }
    var HTMLG21ResponsiveImageElement: {
        prototype: HTMLG21ResponsiveImageElement;
        new (): HTMLG21ResponsiveImageElement;
    };
    interface HTMLElementTagNameMap {
        "g21-responsive-image": HTMLG21ResponsiveImageElement;
    }
}
declare namespace LocalJSX {
    interface G21ResponsiveImage {
    }
    interface IntrinsicElements {
        "g21-responsive-image": G21ResponsiveImage;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "g21-responsive-image": LocalJSX.G21ResponsiveImage & JSXBase.HTMLAttributes<HTMLG21ResponsiveImageElement>;
        }
    }
}
